### ISSUE TITLE
Unused parameters ac and av in lemin()

### ISSUE THREAD

**Issue by 42lan** [42lan/lem-in#13]
https://github.com/4slan/lem-in/blob/370d56b2fa0263f8c65b021dffcbafc1d805f37d/sources/lemin.c#L23

`-Wno-unused-parameter` suppress/disable the unused variable warnings.
Should be removed!

**Comment by 4slan** [comment]
Correct on 523cddcb8dae60f330f69e9f8612caeb621d376b
